services:
  s-ui:
    image: ghcr.io/alireza0/s-ui:${IMAGE_TAG:-v1.3.9}
    environment:
      - SUI_LOG_LEVEL=${SUI_LOG_LEVEL:-info}
      - SUI_DEBUG=${SUI_DEBUG:-false}
    volumes:
      - "./data/db-${NODE_NAME:-default}:/app/db"
      - "../singbox/geodata:/app/geodata"
      - "../certbot/certbot-etc/:/app/cert"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN # for wireguard compatibility
    # ports:
    #   - 80:80
    #   - 443:443
    #   - 2096:2096
    #   - 2095:2095
    logging:
      options:
        max-size: "50m"
        max-file: "1"
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "-v", "127.0.0.1", "80"]
    #   interval: 20s
    #   timeout: 5s
    #   retries: 7
    #   start_period: 10s
