name: pingtunnel

services:
  server:
    image: esrrhs/pingtunnel
    container_name: pingtunnel-server
    cpu_shares: ${PINGTUNNEL_SERVER_CPU_LIMIT:-1000}
    deploy:
      resources:
        limits:
          memory: ${PINGTUNNEL_SERVER_MEMORY_LIMIT:-1000m}
    # privileged: true
    network_mode: host
    restart: always
    command: /pingtunnel
      -type server 
      -nolog 1
      -key ${PINGTUNNEL_KEY}
      -maxconn ${PINGTUNNEL_SERVER_MAXCONN:-0}

  client:
    image: ${IMAGE_REGISTRY}esrrhs/pingtunnel
    container_name: pingtunnel-client
    restart: always
    ports:
      - 127.0.0.1:${PINGTUNNEL_CLIENT_SOCKS_LISTEN_PORT:-1080}:1080
    command: /pingtunnel
      -type client
      -nolog 1
      -l :1080
      -sock5 1
      -tcp_mw ${PINGTUNNEL_CLIENT_TCP_MAX_WINDOW:-20000}
      -key ${PINGTUNNEL_KEY}
      -s ${PINGTUNNEL_CLIENT_SERVER_ADDRESS}
